all:
	cd protoc~1 && $(MAKE) && cd ..
	cd protoc~2 && $(MAKE) && cd ..
	cd protoc~3 && $(MAKE) && cd ..

clean:
	cd protoc~1 && $(MAKE) clean && cd ..
	cd protoc~2 && $(MAKE) clean && cd ..
	cd protoc~3 && $(MAKE) clean && cd ..
