all:
	cd Protocols_from_lab_manuals_or_kits && $(MAKE) && cd ..
	cd Protocols_from_OpenWetWare && $(MAKE) && cd ..
	cd Protocols_from_Published_Papers && $(MAKE) && cd ..

clean:
	cd Protocols_from_lab_manuals_or_kits && $(MAKE) clean && cd ..
	cd Protocols_from_OpenWetWare && $(MAKE) clean && cd ..
	cd Protocols_from_Published_Papers && $(MAKE) clean && cd ..
